default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: h4rdc0r3
  host: localhost

development:
  <<: *default
  database: grow_opp_dev

test:
  <<: *default
  database: grow_opp_test